@startuml


title TwelveDataAdapter

package "demo-twelvedata-service-layer: TwelveDataAdapter" {
    !include Services/TwelveDataServiceLocator.puml
    !include Services/TwelveDataApiKeyService.puml

}


@enduml